### ISSUE TITLE
Server Crash because a Spider has the spell Eagle eye in our 1.12.2 Modpack

### ISSUE THREAD

**Issue by 00Buster** [WinDanesz/AncientSpellcraft#18] opened 2021-03-07 19:14 UTC
[20:08:34] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at com.windanesz.ancientspellcraft.potion.PotionEagleEye.isReady(PotionEagleEye.java:28) ~[PotionEagleEye.class:?]
        at net.minecraft.potion.PotionEffect.onUpdate(PotionEffect.java:117) ~[va.class:?]
        at net.minecraft.entity.EntityLivingBase.updatePotionEffects(EntityLivingBase.java:606) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:353) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.onEntityUpdate(EntityLiving.java:208) ~[vq.class:?]
        at net.minecraft.entity.Entity.onUpdate(Entity.java:389) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2096) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295) ~[vq.class:?]
        at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50) ~[ade.class:?]
        at net.minecraft.entity.monster.EntitySpider.onUpdate(EntitySpider.java:85) ~[adn.class:?]
        at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
        at net.minecraft.world.World.redirect$zbc000$updateEntity(World.java:4123) ~[amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1762) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at com.windanesz.ancientspellcraft.potion.PotionEagleEye.isReady(PotionEagleEye.java:28) ~[PotionEagleEye.class:?]
        at net.minecraft.potion.PotionEffect.onUpdate(PotionEffect.java:117) ~[va.class:?]
        at net.minecraft.entity.EntityLivingBase.updatePotionEffects(EntityLivingBase.java:606) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:353) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.onEntityUpdate(EntityLiving.java:208) ~[vq.class:?]
        at net.minecraft.entity.Entity.onUpdate(Entity.java:389) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2096) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295) ~[vq.class:?]
        at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50) ~[ade.class:?]
        at net.minecraft.entity.monster.EntitySpider.onUpdate(EntitySpider.java:85) ~[adn.class:?]
        at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
        at net.minecraft.world.World.redirect$zbc000$updateEntity(World.java:4123) ~[amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1762) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@3ffb3598 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at com.windanesz.ancientspellcraft.potion.PotionEagleEye.isReady(PotionEagleEye.java:28) ~[PotionEagleEye.class:?]
        at net.minecraft.potion.PotionEffect.onUpdate(PotionEffect.java:117) ~[va.class:?]
        at net.minecraft.entity.EntityLivingBase.updatePotionEffects(EntityLivingBase.java:606) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:353) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.onEntityUpdate(EntityLiving.java:208) ~[vq.class:?]
        at net.minecraft.entity.Entity.onUpdate(Entity.java:389) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2096) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295) ~[vq.class:?]
        at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50) ~[ade.class:?]
        at net.minecraft.entity.monster.EntitySpider.onUpdate(EntitySpider.java:85) ~[adn.class:?]
        at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
        at net.minecraft.world.World.redirect$zbc000$updateEntity(World.java:4123) ~[amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1762) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at com.windanesz.ancientspellcraft.potion.PotionEagleEye.isReady(PotionEagleEye.java:28) ~[PotionEagleEye.class:?]
        at net.minecraft.potion.PotionEffect.onUpdate(PotionEffect.java:117) ~[va.class:?]
        at net.minecraft.entity.EntityLivingBase.updatePotionEffects(EntityLivingBase.java:606) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:353) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.onEntityUpdate(EntityLiving.java:208) ~[vq.class:?]
        at net.minecraft.entity.Entity.onUpdate(Entity.java:389) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2096) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295) ~[vq.class:?]
        at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50) ~[ade.class:?]
        at net.minecraft.entity.monster.EntitySpider.onUpdate(EntitySpider.java:85) ~[adn.class:?]
        at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
        at net.minecraft.world.World.redirect$zbc000$updateEntity(World.java:4123) ~[amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1762) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[20:08:34] [Server thread/ERROR] [

**Comment by Havok66** [comment] 2021-03-13 21:05
**Having the same issue with mobs using Eagle Eye.
MC 1.12.2
Ancient Spellcraft 1.1.2
Let me know if additional info is needed.**

Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at com.windanesz.ancientspellcraft.potion.PotionEagleEye.isReady(PotionEagleEye.java:28)
    at net.minecraft.potion.PotionEffect.onUpdate(PotionEffect.java:117)
    at net.minecraft.entity.EntityLivingBase.updatePotionEffects(EntityLivingBase.java:606)
    at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:353)
    at net.minecraft.entity.EntityLiving.onEntityUpdate(EntityLiving.java:208)
    at net.minecraft.entity.Entity.onUpdate(Entity.java:389)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2096)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$updateEntity$zbd000(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 20 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@13da7ab0 from coremod FMLCorePlugin
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 22 more
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
    ... 24 more

**Comment by WinDanesz** [comment] 2021-03-14 15:48
Fixed in 1.1.3
https://www.curseforge.com/minecraft/mc-mods/ancient-spellcraft/files/3238582

**Closed by WinDanesz** 2021-03-14 15:48 UTC
