### ISSUE TITLE
Summon Skeleton Horse not from wand kicking players from server

### ISSUE THREAD

**Issue by Hensik** [WinDanesz/AncientSpellcraft#34] opened 2021-06-23 22:27 UTC
Using the spell Summon Skeleton Horse from a wand kicks me from a server but doesn't cause the server itself to crash, meaning I can log back in without a problem but as soon as I try again, the same thing happens. Since I'm only getting kicked though, there's no error log. Below is a youtube video of it happening.

Mod versions--
forge-1.12.2-14.23.5.2855
ancientspellcraft-1.1.3
ElectroblobsWizardry-4.3.4-MC1.12.2

https://youtu.be/1RqtZnibm3Y

**Comment by WinDanesz** [comment] 2021-07-28 09:40
duplicate of #27 
fixed in 32b638ef5e768867deda7ccf978c2fe505c8ae8e

**Closed by WinDanesz** 2021-07-28 09:40 UTC
