### ISSUE TITLE
Crash when Placing Ingredients for Ancient Spell

### ISSUE THREAD

**Issue by DoctorZoe** [WinDanesz/AncientSpellcraft#53] opened 2021-09-01 21:28 UTC
Sometimes, when placing items on the Scribing Desk, the game crashes.
Originally, I though it was when placing the ingredients out of order, but even when doing them in order it happens now.
The only solution I found so far was to break the desk and replace it, which seems to work all the time for a new discovery.

Time: 2021-09-01 18:23:45 BRT
Description: Rendering screen
 
java.lang.ArrayIndexOutOfBoundsException
 
A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------
 
-- Screen render details --
  Screen name: com.windanesz.ancientspellcraft.client.gui.GuiScribingDesk
  Mouse location: Scaled: (337, 156). Absolute: (1011, 609)
  Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3

Full crash log below:
https://pastebin.com/rV1jfDMg

**Comment by WinDanesz** [comment] 2021-09-02 07:46
Duplicate of #39

**Closed as completed** 2021-09-06 07:50 UTC
