### ISSUE TITLE
Summon Quicksand crash

### ISSUE THREAD

**Issue by Pelirow** [WinDanesz/AncientSpellcraft#46] opened 2021-07-28 14:17 UTC
[crash-2021-07-28_07.15.49-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/6893780/crash-2021-07-28_07.15.49-server.txt)

Pointed at a stone block, spell channeled, then crash. Was deep underground with floating entities on the ground from mining, if that matters.

EDIT: Re-entering the world, you'll see a single block of quicksand. I tested the scroll of quicksand summoning and it didn't crash the game, but also only summoned a single block of quicksand. I tested the spellbook and scroll of quicksand ring and both appeared to work properly (although it wasn't quite a "ring" around me)

**Comment by WinDanesz** [comment] 2021-07-28 17:51
duplicate of #43

**Closed as completed by WinDanesz** 2021-07-28 17:51 UTC
Labels: bug
