### ISSUE TITLE
when world loaded,it caused a crash (loot initialization, zettai grimoires related?)

### ISSUE THREAD

**Issue by JamesChang20022** [WinDanesz/AncientSpellcraft#66] opened 2021-12-19 09:56 UTC
there's crash report:
https://gist.github.com/JamesChang20022/8801566c64499982b4f62ac931fa9f9d#file-gistfile1-txt
and latest log:
https://gist.github.com/JamesChang20022/3c0a150d252dc00a6ab97e8a76a7be9a

sorry but i can't get any ideas about why caused the crash...except it may related to ancientspell craft loot table

**Comment by WinDanesz** [comment] 2021-12-19 11:11
Does this happen when you start the game and you load a world for the first time, or is it only occurring after saving and switching/reopening worlds in a single game session (=not closing the client)?

**Comment by JamesChang20022** [comment] 2021-12-19 13:44
This modpack i have signed many time but it havent happened until yesterday.it happens when first starting the world，although now i knew it may caused by other mods.

**Comment by WinDanesz** [comment] 2022-04-15 13:33
According to a recent player report, this issue seems to be caused by "Zettai Grimoires". If still persists, please contact the author of that mod.

**Closed as completed by WinDanesz** 2022-04-15 13:33 UTC
Labels: invalid, incompatibility
